import type { Metadata } from "next";
import StyledComponentsRegistry from './lib/registry'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from './lib/theme';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
      <ThemeProvider {...{theme}}>
        <AppRouterCacheProvider>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </AppRouterCacheProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
